In [2]:
import csv
import sqlite3
import pandas as pd

In [3]:
# Creamos la base de datos
connection = sqlite3.connect('advertising.db')

# Creamos un cursor
cursor = connection.cursor()

In [3]:
# create_table = '''CREATE TABLE datos(
#                 TV INTEGER NOT NULL,
#                 radio INTEGER NOT NULL,
#                 newspaper INTEGER NOT NULL,
#                 sales INTEGER NOT NULL);
#                 '''


# # Creamos la tabla dentro de nuestra base de datos
# cursor.execute(create_table)

In [3]:
file = open('data/Advertising.csv')

In [4]:
# leemos el contenido del archivo csv
contents = csv.reader(file)

# query de SQL para insertar los valores de la tabla dentro de la tabla
insert_records = "INSERT INTO datos VALUES(?, ?, ?, ?)"

cursor.executemany(insert_records, contents)

In [5]:
# Query de SQL para verificar los datos insertados en la tabla

borrar_encabezado_extra = "DELETE FROM datos WHERE TV = 'TV'"
rows_2 = cursor.execute(borrar_encabezado_extra).fetchall()
  
# Output to the console screen
for r in rows_2:
    print(r)
  
# Commiting the changes
connection.commit()

In [6]:
# Query de SQL para verificar los datos insertados en la tabla
select_all = "SELECT * FROM datos"
rows = cursor.execute(select_all).fetchall()
  
# Output to the console screen
for r in rows:
    print(r)
  
# Commiting the changes
connection.commit()

(230.1, 37.8, 69.2, 22100)
(44.5, 39.3, 45.1, 10400)
(17.2, 45.9, 69.3, 9300)
(151.5, 41.3, 58.5, 18500)
(180.8, 10.8, 58.4, 12900)
(8.7, 48.9, 75, 7200)
(57.5, 32.8, 23.5, 11800)
(120.2, 19.6, 11.6, 13200)
(8.6, 2.1, 1, 4800)
(199.8, 2.6, 21.2, 10600)
(66.1, 5.8, 24.2, 8600)
(214.7, 24, 4, 17400)
(23.8, 35.1, 65.9, 9200)
(97.5, 7.6, 7.2, 9700)
(204.1, 32.9, 46, 19000)
(195.4, 47.7, 52.9, 22400)
(67.8, 36.6, 114, 12500)
(281.4, 39.6, 55.8, 24400)
(69.2, 20.5, 18.3, 11300)
(147.3, 23.9, 19.1, 14600)
(218.4, 27.7, 53.4, 18000)
(237.4, 5.1, 23.5, 12500)
(13.2, 15.9, 49.6, 5600)
(228.3, 16.9, 26.2, 15500)
(62.3, 12.6, 18.3, 9700)
(262.9, 3.5, 19.5, 12000)
(142.9, 29.3, 12.6, 15000)
(240.1, 16.7, 22.9, 15900)
(248.8, 27.1, 22.9, 18900)
(70.6, 16, 40.8, 10500)
(292.9, 28.3, 43.2, 21400)
(112.9, 17.4, 38.6, 11900)
(97.2, 1.5, 30, 9600)
(265.6, 20, 0.3, 17400)
(95.7, 1.4, 7.4, 9500)
(290.7, 4.1, 8.5, 12800)
(266.9, 43.8, 5, 25400)
(74.7, 49.4, 45.7, 14700)
(43.1, 26.7, 35.1, 10100)
(228, 37.7, 32, 21500)
(202.5, 22.3, 31.6, 16600)
(177, 33.4, 38.7, 17100)
(293.6, 27.7, 1.8, 20700)
(206.9, 8.4, 26.4, 12900)
(25.1, 25.7, 43.3, 8500)
(175.1, 22.5, 31.5, 14900)
(89.7, 9.9, 35.7, 10600)
(239.9, 41.5, 18.5, 23200)
(227.2, 15.8, 49.9, 14800)
(66.9, 11.7, 36.8, 9700)
(199.8, 3.1, 34.6, 11400)
(100.4, 9.6, 3.6, 10700)
(216.4, 41.7, 39.6, 22600)
(182.6, 46.2, 58.7, 21200)
(262.7, 28.8, 15.9, 20200)
(198.9, 49.4, 60, 23700)
(7.3, 28.1, 41.4, 5500)
(136.2, 19.2, 16.6, 13200)
(210.8, 49.6, 37.7, 23800)
(210.7, 29.5, 9.3, 18400)
(53.5, 2, 21.4, 8100)
(261.3, 42.7, 54.7, 24200)
(239.3, 15.5, 27.3, 15700)
(102.7, 29.6, 8.4, 14000)
(131.1, 42.8, 28.9, 18000)
(69, 9.3, 0.9, 9300)
(31.5, 24.6, 2.2, 9500)
(139.3, 14.5, 10.2, 13400)
(237.4, 27.5, 11, 18900)
(216.8, 43.9, 27.2, 22300)
(199.1, 30.6, 38.7, 18300)
(109.8, 14.3, 31.7, 12400)
(26.8, 33, 19.3, 8800)
(129.4, 5.7, 31.3, 11000)
(213.4, 24.6, 13.1, 17000)
(16.9, 43.7, 89.4, 8700)
(27.5, 1.6, 20.7, 6900)
(120.5, 28.5, 14.2, 14200)
(5.4, 29.9, 9.4, 5300)
(116, 7.7, 23.1, 11000)
(76.4, 26.7, 22.3, 11800)
(239.8, 4.1, 36.9, 12300)
(75.3, 20.3, 32.5, 11300)
(68.4, 44.5, 35.6, 13600)
(213.5, 43, 33.8, 21700)
(193.2, 18.4, 65.7, 15200)
(76.3, 27.5, 16, 12000)
(110.7, 40.6, 63.2, 16000)
(88.3, 25.5, 73.4, 12900)
(109.8, 47.8, 51.4, 16700)
(134.3, 4.9, 9.3, 11200)
(28.6, 1.5, 33, 7300)
(217.7, 33.5, 59, 19400)
(250.9, 36.5, 72.3, 22200)
(107.4, 14, 10.9, 11500)
(163.3, 31.6, 52.9, 16900)
(197.6, 3.5, 5.9, 11700)
(184.9, 21, 22, 15500)
(289.7, 42.3, 51.2, 25400)
(135.2, 41.7, 45.9, 17200)
(222.4, 4.3, 49.8, 11700)
(296.4, 36.3, 100.9, 23800)
(280.2, 10.1, 21.4, 14800)
(187.9, 17.2, 17.9, 14700)
(238.2, 34.3, 5.3, 20700)
(137.9, 46.4, 59, 19200)
(25, 11, 29.7, 7200)
(90.4, 0.3, 23.2, 8700)
(13.1, 0.4, 25.6, 5300)
(255.4, 26.9, 5.5, 19800)
(225.8, 8.2, 56.5, 13400)
(241.7, 38, 23.2, 21800)
(175.7, 15.4, 2.4, 14100)
(209.6, 20.6, 10.7, 15900)
(78.2, 46.8, 34.5, 14600)
(75.1, 35, 52.7, 12600)
(139.2, 14.3, 25.6, 12200)
(76.4, 0.8, 14.8, 9400)
(125.7, 36.9, 79.2, 15900)
(19.4, 16, 22.3, 6600)
(141.3, 26.8, 46.2, 15500)
(18.8, 21.7, 50.4, 7000)
(224, 2.4, 15.6, 11600)
(123.1, 34.6, 12.4, 15200)
(229.5, 32.3, 74.2, 19700)
(87.2, 11.8, 25.9, 10600)
(7.8, 38.9, 50.6, 6600)
(80.2, 0, 9.2, 8800)
(220.3, 49, 3.2, 24700)
(59.6, 12, 43.1, 9700)
(0.7, 39.6, 8.7, 1600)
(265.2, 2.9, 43, 12700)
(8.4, 27.2, 2.1, 5700)
(219.8, 33.5, 45.1, 19600)
(36.9, 38.6, 65.6, 10800)
(48.3, 47, 8.5, 11600)
(25.6, 39, 9.3, 9500)
(273.7, 28.9, 59.7, 20800)
(43, 25.9, 20.5, 9600)
(184.9, 43.9, 1.7, 20700)
(73.4, 17, 12.9, 10900)
(193.7, 35.4, 75.6, 19200)
(220.5, 33.2, 37.9, 20100)
(104.6, 5.7, 34.4, 10400)
(96.2, 14.8, 38.9, 11400)
(140.3, 1.9, 9, 10300)
(240.1, 7.3, 8.7, 13200)
(243.2, 49, 44.3, 25400)
(38, 40.3, 11.9, 10900)
(44.7, 25.8, 20.6, 10100)
(280.7, 13.9, 37, 16100.000000000002)
(121, 8.4, 48.7, 11600)
(197.6, 23.3, 14.2, 16600)
(171.3, 39.7, 37.7, 19000)
(187.8, 21.1, 9.5, 15600)
(4.1, 11.6, 5.7, 3200)
(93.9, 43.5, 50.5, 15300)
(149.8, 1.3, 24.3, 10100)
(11.7, 36.9, 45.2, 7300)
(131.7, 18.4, 34.6, 12900)
(172.5, 18.1, 30.7, 14400)
(85.7, 35.8, 49.3, 13300)
(188.4, 18.1, 25.6, 14900)
(163.5, 36.8, 7.4, 18000)
(117.2, 14.7, 5.4, 11900)
(234.5, 3.4, 84.8, 11900)
(17.9, 37.6, 21.6, 8000)
(206.8, 5.2, 19.4, 12200)
(215.4, 23.6, 57.6, 17100)
(284.3, 10.6, 6.4, 15000)
(50, 11.6, 18.4, 8400)
(164.5, 20.9, 47.4, 14500)
(19.6, 20.1, 17, 7600)
(168.4, 7.1, 12.8, 11700)
(222.4, 3.4, 13.1, 11500)
(276.9, 48.9, 41.8, 27000)
(248.4, 30.2, 20.3, 20200)
(170.2, 7.8, 35.2, 11700)
(276.7, 2.3, 23.7, 11800)
(165.6, 10, 17.6, 12600)
(156.6, 2.6, 8.3, 10500)
(218.5, 5.4, 27.4, 12200)
(56.2, 5.7, 29.7, 8700)
(287.6, 43, 71.8, 26200)
(253.8, 21.3, 30, 17600)
(205, 45.1, 19.6, 22600)
(139.5, 2.1, 26.6, 10300)
(191.1, 28.7, 18.2, 17300)
(286, 13.9, 3.7, 15900)
(18.7, 12.1, 23.4, 6700)
(39.5, 41.1, 5.8, 10800)
(75.5, 10.8, 6, 9900)
(17.2, 4.1, 31.6, 5900)
(166.8, 42, 3.6, 19600)
(149.7, 35.6, 6, 17300)
(38.2, 3.7, 13.8, 7600)
(94.2, 4.9, 8.1, 9700)
(177, 9.3, 6.4, 12800)
(283.6, 42, 66.2, 25500)
(232.1, 8.6, 8.7, 13400)
(200, 20, 20, 20000)
(150, 15, 15, 15000)
(230.1, 37.8, 69.2, 22100)
(44.5, 39.3, 45.1, 10400)
(17.2, 45.9, 69.3, 9300)
(151.5, 41.3, 58.5, 18500)
(180.8, 10.8, 58.4, 12900)
(8.7, 48.9, 75, 7200)
(57.5, 32.8, 23.5, 11800)
(120.2, 19.6, 11.6, 13200)
(8.6, 2.1, 1, 4800)
(199.8, 2.6, 21.2, 10600)
(66.1, 5.8, 24.2, 8600)
(214.7, 24, 4, 17400)
(23.8, 35.1, 65.9, 9200)
(97.5, 7.6, 7.2, 9700)
(204.1, 32.9, 46, 19000)
(195.4, 47.7, 52.9, 22400)
(67.8, 36.6, 114, 12500)
(281.4, 39.6, 55.8, 24400)
(69.2, 20.5, 18.3, 11300)
(147.3, 23.9, 19.1, 14600)
(218.4, 27.7, 53.4, 18000)
(237.4, 5.1, 23.5, 12500)
(13.2, 15.9, 49.6, 5600)
(228.3, 16.9, 26.2, 15500)
(62.3, 12.6, 18.3, 9700)
(262.9, 3.5, 19.5, 12000)
(142.9, 29.3, 12.6, 15000)
(240.1, 16.7, 22.9, 15900)
(248.8, 27.1, 22.9, 18900)
(70.6, 16, 40.8, 10500)
(292.9, 28.3, 43.2, 21400)
(112.9, 17.4, 38.6, 11900)
(97.2, 1.5, 30, 9600)
(265.6, 20, 0.3, 17400)
(95.7, 1.4, 7.4, 9500)
(290.7, 4.1, 8.5, 12800)
(266.9, 43.8, 5, 25400)
(74.7, 49.4, 45.7, 14700)
(43.1, 26.7, 35.1, 10100)
(228, 37.7, 32, 21500)
(202.5, 22.3, 31.6, 16600)
(177, 33.4, 38.7, 17100)
(293.6, 27.7, 1.8, 20700)
(206.9, 8.4, 26.4, 12900)
(25.1, 25.7, 43.3, 8500)
(175.1, 22.5, 31.5, 14900)
(89.7, 9.9, 35.7, 10600)
(239.9, 41.5, 18.5, 23200)
(227.2, 15.8, 49.9, 14800)
(66.9, 11.7, 36.8, 9700)
(199.8, 3.1, 34.6, 11400)
(100.4, 9.6, 3.6, 10700)
(216.4, 41.7, 39.6, 22600)
(182.6, 46.2, 58.7, 21200)
(262.7, 28.8, 15.9, 20200)
(198.9, 49.4, 60, 23700)
(7.3, 28.1, 41.4, 5500)
(136.2, 19.2, 16.6, 13200)
(210.8, 49.6, 37.7, 23800)
(210.7, 29.5, 9.3, 18400)
(53.5, 2, 21.4, 8100)
(261.3, 42.7, 54.7, 24200)
(239.3, 15.5, 27.3, 15700)
(102.7, 29.6, 8.4, 14000)
(131.1, 42.8, 28.9, 18000)
(69, 9.3, 0.9, 9300)
(31.5, 24.6, 2.2, 9500)
(139.3, 14.5, 10.2, 13400)
(237.4, 27.5, 11, 18900)
(216.8, 43.9, 27.2, 22300)
(199.1, 30.6, 38.7, 18300)
(109.8, 14.3, 31.7, 12400)
(26.8, 33, 19.3, 8800)
(129.4, 5.7, 31.3, 11000)
(213.4, 24.6, 13.1, 17000)
(16.9, 43.7, 89.4, 8700)
(27.5, 1.6, 20.7, 6900)
(120.5, 28.5, 14.2, 14200)
(5.4, 29.9, 9.4, 5300)
(116, 7.7, 23.1, 11000)
(76.4, 26.7, 22.3, 11800)
(239.8, 4.1, 36.9, 12300)
(75.3, 20.3, 32.5, 11300)
(68.4, 44.5, 35.6, 13600)
(213.5, 43, 33.8, 21700)
(193.2, 18.4, 65.7, 15200)
(76.3, 27.5, 16, 12000)
(110.7, 40.6, 63.2, 16000)
(88.3, 25.5, 73.4, 12900)
(109.8, 47.8, 51.4, 16700)
(134.3, 4.9, 9.3, 11200)
(28.6, 1.5, 33, 7300)
(217.7, 33.5, 59, 19400)
(250.9, 36.5, 72.3, 22200)
(107.4, 14, 10.9, 11500)
(163.3, 31.6, 52.9, 16900)
(197.6, 3.5, 5.9, 11700)
(184.9, 21, 22, 15500)
(289.7, 42.3, 51.2, 25400)
(135.2, 41.7, 45.9, 17200)
(222.4, 4.3, 49.8, 11700)
(296.4, 36.3, 100.9, 23800)
(280.2, 10.1, 21.4, 14800)
(187.9, 17.2, 17.9, 14700)
(238.2, 34.3, 5.3, 20700)
(137.9, 46.4, 59, 19200)
(25, 11, 29.7, 7200)
(90.4, 0.3, 23.2, 8700)
(13.1, 0.4, 25.6, 5300)
(255.4, 26.9, 5.5, 19800)
(225.8, 8.2, 56.5, 13400)
(241.7, 38, 23.2, 21800)
(175.7, 15.4, 2.4, 14100)
(209.6, 20.6, 10.7, 15900)
(78.2, 46.8, 34.5, 14600)
(75.1, 35, 52.7, 12600)
(139.2, 14.3, 25.6, 12200)
(76.4, 0.8, 14.8, 9400)
(125.7, 36.9, 79.2, 15900)
(19.4, 16, 22.3, 6600)
(141.3, 26.8, 46.2, 15500)
(18.8, 21.7, 50.4, 7000)
(224, 2.4, 15.6, 11600)
(123.1, 34.6, 12.4, 15200)
(229.5, 32.3, 74.2, 19700)
(87.2, 11.8, 25.9, 10600)
(7.8, 38.9, 50.6, 6600)
(80.2, 0, 9.2, 8800)
(220.3, 49, 3.2, 24700)
(59.6, 12, 43.1, 9700)
(0.7, 39.6, 8.7, 1600)
(265.2, 2.9, 43, 12700)
(8.4, 27.2, 2.1, 5700)
(219.8, 33.5, 45.1, 19600)
(36.9, 38.6, 65.6, 10800)
(48.3, 47, 8.5, 11600)
(25.6, 39, 9.3, 9500)
(273.7, 28.9, 59.7, 20800)
(43, 25.9, 20.5, 9600)
(184.9, 43.9, 1.7, 20700)
(73.4, 17, 12.9, 10900)
(193.7, 35.4, 75.6, 19200)
(220.5, 33.2, 37.9, 20100)
(104.6, 5.7, 34.4, 10400)
(96.2, 14.8, 38.9, 11400)
(140.3, 1.9, 9, 10300)
(240.1, 7.3, 8.7, 13200)
(243.2, 49, 44.3, 25400)
(38, 40.3, 11.9, 10900)
(44.7, 25.8, 20.6, 10100)
(280.7, 13.9, 37, 16100.000000000002)
(121, 8.4, 48.7, 11600)
(197.6, 23.3, 14.2, 16600)
(171.3, 39.7, 37.7, 19000)
(187.8, 21.1, 9.5, 15600)
(4.1, 11.6, 5.7, 3200)
(93.9, 43.5, 50.5, 15300)
(149.8, 1.3, 24.3, 10100)
(11.7, 36.9, 45.2, 7300)
(131.7, 18.4, 34.6, 12900)
(172.5, 18.1, 30.7, 14400)
(85.7, 35.8, 49.3, 13300)
(188.4, 18.1, 25.6, 14900)
(163.5, 36.8, 7.4, 18000)
(117.2, 14.7, 5.4, 11900)
(234.5, 3.4, 84.8, 11900)
(17.9, 37.6, 21.6, 8000)
(206.8, 5.2, 19.4, 12200)
(215.4, 23.6, 57.6, 17100)
(284.3, 10.6, 6.4, 15000)
(50, 11.6, 18.4, 8400)
(164.5, 20.9, 47.4, 14500)
(19.6, 20.1, 17, 7600)
(168.4, 7.1, 12.8, 11700)
(222.4, 3.4, 13.1, 11500)
(276.9, 48.9, 41.8, 27000)
(248.4, 30.2, 20.3, 20200)
(170.2, 7.8, 35.2, 11700)
(276.7, 2.3, 23.7, 11800)
(165.6, 10, 17.6, 12600)
(156.6, 2.6, 8.3, 10500)
(218.5, 5.4, 27.4, 12200)
(56.2, 5.7, 29.7, 8700)
(287.6, 43, 71.8, 26200)
(253.8, 21.3, 30, 17600)
(205, 45.1, 19.6, 22600)
(139.5, 2.1, 26.6, 10300)
(191.1, 28.7, 18.2, 17300)
(286, 13.9, 3.7, 15900)
(18.7, 12.1, 23.4, 6700)
(39.5, 41.1, 5.8, 10800)
(75.5, 10.8, 6, 9900)
(17.2, 4.1, 31.6, 5900)
(166.8, 42, 3.6, 19600)
(149.7, 35.6, 6, 17300)
(38.2, 3.7, 13.8, 7600)
(94.2, 4.9, 8.1, 9700)
(177, 9.3, 6.4, 12800)
(283.6, 42, 66.2, 25500)
(232.1, 8.6, 8.7, 13400)

In [ ]:
## PRUEBAS

In [4]:
tv = 150
radio = 15
newspaper = 15
sales = 15000

connection = sqlite3.connect('advertising.db')
cursor = connection.cursor()

query = '''
INSERT INTO datos
(TV, radio, newspaper, sales)
VALUES (?,?,?,?)
'''

cursor.execute(query, (tv, radio, newspaper, sales)).fetchall()
connection.commit()


print('Has añadido los siguientes datos ' + str(tv) + ', ' + str(radio) + ', ' + str(newspaper) + ', ' + str(sales))

Has añadido los siguientes datos 150, 15, 15, 15000

In [9]:
def sql_query(query):

    # Ejecuta la query
    cursor.execute(query)

    # Almacena los datos de la query 
    ans = cursor.fetchall()

    # Obtenemos los nombres de las columnas de la tabla
    names = [description[0] for description in cursor.description]

    return pd.DataFrame(ans,columns=names)

query = '''
SELECT * 
FROM datos
'''


df = sql_query(query)
df

        TV  radio  newspaper    sales
0    230.1   37.8       69.2  22100.0
1     44.5   39.3       45.1  10400.0
2     17.2   45.9       69.3   9300.0
3    151.5   41.3       58.5  18500.0
4    180.8   10.8       58.4  12900.0
..     ...    ...        ...      ...
398   94.2    4.9        8.1   9700.0
399  177.0    9.3        6.4  12800.0
400  283.6   42.0       66.2  25500.0
401  232.1    8.6        8.7  13400.0
402  150.0   15.0       15.0  15000.0

[403 rows x 4 columns]

In [7]:
import pickle
from flask import jsonify
import datetime

In [10]:
# def retrain():

#     def sql_query(query):
#         connection = sqlite3.connect('advertising.db')
#         cursor = connection.cursor()
#         cursor.execute(query)
#         ans = cursor.fetchall()
#         names = [description[0] for description in cursor.description]

#         return pd.DataFrame(ans,columns=names)
#     df = sql_query('''SELECT * FROM datos''')

#     print(df)

#     X = df.drop(columns=['sales'])
#     y = df['sales']

#     model = pickle.load(open('data/advertising_model','rb'))
#     model.fit(X,y)

#     nombre_modelo = 'data/advertising_retrain_mod' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

#     # pickle.dump(model, open('data/advertising_model_retrain' + datetime.now().strftime("%Y%m%d-%H%M%S"),'wb'))
#     pickle.dump(model, open(nombre_modelo,'wb'))

#     return print('Has reentrenado el modelo con últimos datos añadidos. \n\nCaracterísticas del modelo: ' + str(model))

In [11]:
# retrain()

        TV  radio  newspaper    sales
0    230.1   37.8       69.2  22100.0
1     44.5   39.3       45.1  10400.0
2     17.2   45.9       69.3   9300.0
3    151.5   41.3       58.5  18500.0
4    180.8   10.8       58.4  12900.0
..     ...    ...        ...      ...
195   38.2    3.7       13.8   7600.0
196   94.2    4.9        8.1   9700.0
197  177.0    9.3        6.4  12800.0
198  283.6   42.0       66.2  25500.0
199  232.1    8.6        8.7  13400.0

[200 rows x 4 columns]
Has reentrenado el modelo con últimos datos añadidos.

Características del modelo: Pipeline(steps=[('polynomialfeatures', PolynomialFeatures(degree=3)),
                ('linearregression', LinearRegression())])